# Generic, formatter-friendly config.
exclude = ["distributed/protocol_pb2*.py"]

[lint]
select = ["B", "D", "E", "F", "I", "N", "W"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
# D203 (no-blank-line-before-class) 与 D211 冲突，移除 D203 保留 D211
# D213 (multi-line-summary-second-line) 与 D212 冲突，移除 D213 保留 D212
ignore = ["E501", "D203", "D213"]
