# Generic, formatter-friendly config.
select = ["B", "D", "E", "F", "I", "N", "W"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
ignore = ["E501"]

# 排除 protobuf 自动生成的代码
exclude = ["distributed/protocol_pb2*.py"]
