# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from distributed import protocol_pb2 as distributed_dot_protocol__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION,
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in distributed/protocol_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.",
    )


class MasterServiceStub:
    """─────────────────────────────────────────────────────────────
    MasterService — 分布式碰撞扫描 gRPC 协议
    ─────────────────────────────────────────────────────────────.
    """

    def __init__(self, channel) -> None:
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.Register = channel.unary_unary(
            "/distributed.MasterService/Register",
            request_serializer=distributed_dot_protocol__pb2.RegisterRequest.SerializeToString,
            response_deserializer=distributed_dot_protocol__pb2.RegisterResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/distributed.MasterService/Heartbeat",
            request_serializer=distributed_dot_protocol__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=distributed_dot_protocol__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )
        self.GetAssignment = channel.unary_unary(
            "/distributed.MasterService/GetAssignment",
            request_serializer=distributed_dot_protocol__pb2.AssignmentRequest.SerializeToString,
            response_deserializer=distributed_dot_protocol__pb2.AssignmentResponse.FromString,
            _registered_method=True,
        )
        self.ReportHit = channel.unary_unary(
            "/distributed.MasterService/ReportHit",
            request_serializer=distributed_dot_protocol__pb2.HitReport.SerializeToString,
            response_deserializer=distributed_dot_protocol__pb2.ReportResponse.FromString,
            _registered_method=True,
        )
        self.GetTargetInfo = channel.unary_unary(
            "/distributed.MasterService/GetTargetInfo",
            request_serializer=distributed_dot_protocol__pb2.TargetInfoRequest.SerializeToString,
            response_deserializer=distributed_dot_protocol__pb2.TargetInfoResponse.FromString,
            _registered_method=True,
        )


class MasterServiceServicer:
    """─────────────────────────────────────────────────────────────
    MasterService — 分布式碰撞扫描 gRPC 协议
    ─────────────────────────────────────────────────────────────.
    """

    def Register(self, request, context):
        """Worker 注册：建立身份并上报能力."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)

    def Heartbeat(self, request, context):
        """心跳 + 进度上报."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)

    def GetAssignment(self, request, context):
        """获取下一个作业范围."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)

    def ReportHit(self, request, context):
        """报告碰撞命中结果."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)

    def GetTargetInfo(self, request, context):
        """获取目标集信息（校验和、下载地址等）."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        msg = "Method not implemented!"
        raise NotImplementedError(msg)


def add_MasterServiceServicer_to_server(servicer, server) -> None:
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=distributed_dot_protocol__pb2.RegisterRequest.FromString,
            response_serializer=distributed_dot_protocol__pb2.RegisterResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=distributed_dot_protocol__pb2.HeartbeatRequest.FromString,
            response_serializer=distributed_dot_protocol__pb2.HeartbeatResponse.SerializeToString,
        ),
        "GetAssignment": grpc.unary_unary_rpc_method_handler(
            servicer.GetAssignment,
            request_deserializer=distributed_dot_protocol__pb2.AssignmentRequest.FromString,
            response_serializer=distributed_dot_protocol__pb2.AssignmentResponse.SerializeToString,
        ),
        "ReportHit": grpc.unary_unary_rpc_method_handler(
            servicer.ReportHit,
            request_deserializer=distributed_dot_protocol__pb2.HitReport.FromString,
            response_serializer=distributed_dot_protocol__pb2.ReportResponse.SerializeToString,
        ),
        "GetTargetInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetTargetInfo,
            request_deserializer=distributed_dot_protocol__pb2.TargetInfoRequest.FromString,
            response_serializer=distributed_dot_protocol__pb2.TargetInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "distributed.MasterService", rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "distributed.MasterService", rpc_method_handlers,
    )


# This class is part of an EXPERIMENTAL API.
class MasterService:
    """─────────────────────────────────────────────────────────────
    MasterService — 分布式碰撞扫描 gRPC 协议
    ─────────────────────────────────────────────────────────────.
    """

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/distributed.MasterService/Register",
            distributed_dot_protocol__pb2.RegisterRequest.SerializeToString,
            distributed_dot_protocol__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/distributed.MasterService/Heartbeat",
            distributed_dot_protocol__pb2.HeartbeatRequest.SerializeToString,
            distributed_dot_protocol__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAssignment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/distributed.MasterService/GetAssignment",
            distributed_dot_protocol__pb2.AssignmentRequest.SerializeToString,
            distributed_dot_protocol__pb2.AssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReportHit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/distributed.MasterService/ReportHit",
            distributed_dot_protocol__pb2.HitReport.SerializeToString,
            distributed_dot_protocol__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTargetInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/distributed.MasterService/GetTargetInfo",
            distributed_dot_protocol__pb2.TargetInfoRequest.SerializeToString,
            distributed_dot_protocol__pb2.TargetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
